### ISSUE TITLE
VirusTotal detects release 0.2.0 windows-latest.zip as a virus

### ISSUE THREAD

**Issue by StrongSand94191** [Terria-K/pyrgos#2]
![image](https://github.com/FortRise/pyrgos/assets/79473173/e1726a0a-c02c-47ef-a498-31b9e4b3d08c)
https://www.virustotal.com/gui/file/62a284c4babf8c0d8ac5b8ac8b94a2bab7df3e10fd9e0414c1155973ddcbae4c
https://github.com/kevoreilly/CAPEv2/issues/1671

**Comment by Terria-K** [comment]
I think this only checks if the executable is signed or not. It does somehow had a different result to me and it just looks false positive.

**Comment by StrongSand94191** [comment]
Sorry, my bad! Thanks for the clarification, my friend was worrying about it
